version: "3"
services: 
    server:
        build: .
        ports: 
            - "5000:5000"
            - "5001:5001"
        volumes:
            - ./:/usr/src/app
        command: npm run debug
            