version: "3"
services: 
    server:
        build: 
            args: 
                - NODE_ENV=development 
            context: .
            dockerfile: Dockerfile
        image: spotmummify:latest
        command: npm run start
        ports: 
            - "5000:5000"
            - "5001:5001"
        environment:
            - SERVER_PORT=5000
        volumes:
            - .:/code
        command: npm run start
            