version: "3"
services: 
    server:
        build: 
            context: .
        ports: 
            - "5000:5000"
            - "5001:5001"
        environment:
            - SERVER_PORT=8080
        volumes:
            - ./:/usr/src/app
        command: npm run debug
            